//! File writer utility for code generation output.

use std::path::Path;

/// Standard header comment for generated files.
fn generated_header() -> &'static str {
    "// This file is auto-generated by nize-codegen from OpenAPI YAML.\n\
     // Do not edit manually.\n\
     \n"
}

/// Write generated code to a file with a standard header comment.
pub fn write_generated_file(path: &Path, content: &str) -> std::io::Result<()> {
    let full = format!("{}{}", generated_header(), content);
    std::fs::write(path, full)
}

/// Escape a string for use in a Rust string literal.
pub fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
