# Composite action to collect PR and commit data for release notes
name: Collect Release Data
description: Collects merged PRs and commits since the last release tag

inputs:
  previous-tag:
    description: 'Previous release tag (e.g., v5.2.0)'
    required: false
    default: ''
  previous-date:
    description: 'Date of the previous release (ISO format)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  pr-list:
    description: 'Formatted list of PRs for release notes'
    value: ${{ steps.prs.outputs.list }}
  pr-urls:
    description: 'Newline-separated PR URLs'
    value: ${{ steps.prs.outputs.urls }}
  linked-issue-urls:
    description: 'Newline-separated linked issue URLs from PRs'
    value: ${{ steps.prs.outputs.linked_issue_urls }}
  commit-log:
    description: 'Formatted commit log for release notes'
    value: ${{ steps.commits.outputs.log }}
  commit-issue-urls:
    description: 'Newline-separated issue URLs from commits'
    value: ${{ steps.commits.outputs.issue_urls }}
  issue-list:
    description: 'Formatted list of issues for release notes'
    value: ${{ steps.issues.outputs.list }}
  contributors:
    description: 'Space-separated list of unique contributor usernames'
    value: ${{ steps.contributors.outputs.list }}

runs:
  using: composite
  steps:
    - name: Get merged PRs since last release
      id: prs
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PREV_DATE: ${{ inputs.previous-date }}
      run: |
        if [ -n "$PREV_DATE" ]; then
          PR_DATA=$(gh pr list \
            --state merged \
            --base main \
            --search "merged:>$PREV_DATE" \
            --json number,title,labels,author,closingIssuesReferences)
        else
          PR_DATA=$(gh pr list \
            --state merged \
            --base main \
            --limit 30 \
            --json number,title,labels,author,closingIssuesReferences)
        fi

        # Format for Claude prompt
        PRS=$(echo "$PR_DATA" | jq -r '.[] | "- PR #\(.number): \(.title) (@\(.author.login)) [labels: \([.labels[].name] | join(", "))]"')
        echo "list<<EOF" >> $GITHUB_OUTPUT
        echo "$PRS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Extract PR URLs for commenting (use full URLs for consistency)
        PR_URLS=$(echo "$PR_DATA" | jq -r '.[].number' | while read NUM; do echo "https://github.com/$GITHUB_REPOSITORY/pull/$NUM"; done)
        echo "urls<<EOF" >> $GITHUB_OUTPUT
        echo "$PR_URLS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Extract linked issue URLs for commenting (use full URLs to support cross-repo issues)
        LINKED_ISSUE_URLS=$(echo "$PR_DATA" | jq -r '.[].closingIssuesReferences[].url // empty' | sort -u)
        echo "linked_issue_urls<<EOF" >> $GITHUB_OUTPUT
        echo "$LINKED_ISSUE_URLS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Get commits since last release
      id: commits
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PREV_TAG: ${{ inputs.previous-tag }}
      run: |
        if [ -n "$PREV_TAG" ]; then
          COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --no-merges)
        else
          COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges -30)
        fi
        echo "log<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMITS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Extract issue references from commit messages for commenting
        if [ -n "$PREV_TAG" ]; then
          COMMIT_MESSAGES=$(git log $PREV_TAG..HEAD --pretty=format:"%s %b")
        else
          COMMIT_MESSAGES=$(git log --pretty=format:"%s %b" -30)
        fi

        # Collect all issue URLs from commits (full URLs, cross-repo refs, and local refs)
        ALL_ISSUE_URLS=""

        # 1. Extract full GitHub issue URLs directly
        FULL_URLS=$(echo "$COMMIT_MESSAGES" | grep -oE 'https://github.com/[^/]+/[^/]+/issues/[0-9]+' | sort -u || true)
        ALL_ISSUE_URLS="$FULL_URLS"

        # 2. Convert cross-repo refs (org/repo#123) to full URLs
        CROSS_REFS=$(echo "$COMMIT_MESSAGES" | grep -oE '[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+#[0-9]+' | sort -u || true)
        for REF in $CROSS_REFS; do
          REPO_PART="${REF%#*}"
          ISSUE_NUM="${REF##*#}"
          ALL_ISSUE_URLS="$ALL_ISSUE_URLS
        https://github.com/${REPO_PART}/issues/${ISSUE_NUM}"
        done

        # 3. Extract local refs (#123) and resolve via GraphQL to determine PR vs Issue
        # Use word boundary to avoid matching cross-repo refs
        LOCAL_REFS=$(echo "$COMMIT_MESSAGES" | grep -oE '(^|[^/])#[0-9]+' | grep -oE '#[0-9]+' | tr -d '#' | sort -u || true)

        if [ -n "$LOCAL_REFS" ]; then
          # Build GraphQL query to resolve all numbers in a single API call
          REPO_OWNER="${GITHUB_REPOSITORY%/*}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"

          QUERY="{ repository(owner: \"$REPO_OWNER\", name: \"$REPO_NAME\") {"
          for NUM in $LOCAL_REFS; do
            QUERY="$QUERY n$NUM: issueOrPullRequest(number: $NUM) { __typename }"
          done
          QUERY="$QUERY }}"

          # Execute GraphQL query and parse results
          # Note: API may return partial data with errors for invalid numbers, so we capture stdout
          # and use empty object as fallback only if no output at all
          RESULT=$(gh api graphql -f query="$QUERY" 2>/dev/null || true)
          if [ -z "$RESULT" ]; then
            RESULT='{"data":{"repository":{}}}'
          fi

          # For each local ref, check if it's an Issue (not a PR) and add to URLs
          for NUM in $LOCAL_REFS; do
            TYPE=$(echo "$RESULT" | jq -r ".data.repository.n$NUM.__typename // \"null\"")
            if [ "$TYPE" = "Issue" ]; then
              ALL_ISSUE_URLS="$ALL_ISSUE_URLS
        https://github.com/${GITHUB_REPOSITORY}/issues/${NUM}"
            fi
            # PRs are ignored (already captured in pr-urls)
            # Invalid/non-existent numbers return null and are discarded
          done
        fi

        # Output deduplicated URLs
        ISSUE_URLS=$(echo "$ALL_ISSUE_URLS" | grep -v '^$' | sort -u || true)
        echo "issue_urls<<EOF" >> $GITHUB_OUTPUT
        echo "$ISSUE_URLS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Format issue list for release notes
      id: issues
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        LINKED_ISSUE_URLS: ${{ steps.prs.outputs.linked_issue_urls }}
        COMMIT_ISSUE_URLS: ${{ steps.commits.outputs.issue_urls }}
      run: |
        # Combine and deduplicate issue URLs
        ALL_ISSUE_URLS=$(printf "%s\n%s\n" "$LINKED_ISSUE_URLS" "$COMMIT_ISSUE_URLS" | grep -v '^$' | sort -u || true)

        ISSUE_LIST=""
        for ISSUE_URL in $ALL_ISSUE_URLS; do
          TITLE=$(gh api "$ISSUE_URL" --jq '.title' 2>/dev/null || echo "")
          if [ -n "$TITLE" ] && [ "$TITLE" != "null" ]; then
            ISSUE_LIST="$ISSUE_LIST\n- $TITLE (Issue $ISSUE_URL)"
          else
            ISSUE_LIST="$ISSUE_LIST\n- Issue $ISSUE_URL"
          fi
        done

        ISSUE_LIST=$(echo "$ISSUE_LIST" | sed '/^$/d')
        echo "list<<EOF" >> $GITHUB_OUTPUT
        echo "$ISSUE_LIST" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Collect contributors from PRs and Issues
      id: contributors
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PREV_DATE: ${{ inputs.previous-date }}
        PR_DATA_JSON: ${{ steps.prs.outputs.list }}
        LINKED_ISSUE_URLS: ${{ steps.prs.outputs.linked_issue_urls }}
        COMMIT_ISSUE_URLS: ${{ steps.commits.outputs.issue_urls }}
      run: |
        # Collect PR authors
        if [ -n "$PREV_DATE" ]; then
          PR_AUTHORS=$(gh pr list \
            --state merged \
            --base main \
            --search "merged:>$PREV_DATE" \
            --json author \
            --jq '.[].author.login')
        else
          PR_AUTHORS=$(gh pr list \
            --state merged \
            --base main \
            --limit 30 \
            --json author \
            --jq '.[].author.login')
        fi

        # Collect issue authors from linked issues
        ALL_CONTRIBUTORS="$PR_AUTHORS"

        # Fetch authors from linked issues
        for ISSUE_URL in $LINKED_ISSUE_URLS $COMMIT_ISSUE_URLS; do
          if [[ "$ISSUE_URL" =~ https://github.com/([^/]+)/([^/]+)/issues/([0-9]+) ]]; then
            OWNER="${BASH_REMATCH[1]}"
            REPO="${BASH_REMATCH[2]}"
            ISSUE_NUM="${BASH_REMATCH[3]}"

            # Fetch issue author using GraphQL (handles cross-repo)
            ISSUE_AUTHOR=$(gh api graphql -f query="
              query {
                repository(owner: \"$OWNER\", name: \"$REPO\") {
                  issue(number: $ISSUE_NUM) {
                    author { login }
                  }
                }
              }" --jq '.data.repository.issue.author.login' 2>/dev/null || true)

            if [ -n "$ISSUE_AUTHOR" ] && [ "$ISSUE_AUTHOR" != "null" ] && [ "$ISSUE_AUTHOR" != "true" ]; then
              ALL_CONTRIBUTORS="$ALL_CONTRIBUTORS
        $ISSUE_AUTHOR"
            fi
          fi
        done

        # Deduplicate, filter out bots/AI agents, and format as space-separated list
        CONTRIBUTORS=$(echo "$ALL_CONTRIBUTORS" | \
          grep -v '^$' | \
          sort -u | \
          grep -viE '(bot|\[bot\]|dependabot|github-actions|renovate)' || true)

        # Convert to space-separated for easier use
        CONTRIBUTORS_LIST=$(echo "$CONTRIBUTORS" | tr '\n' ' ' | sed 's/ $//')

        echo "list=$CONTRIBUTORS_LIST" >> $GITHUB_OUTPUT
